spring:
  application:
    name: eureka-server
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9092/eureka/,http://localhost:9093/eureka/
  instance:
    hostname: localhost:9091
    instance-id: eureka1
