spring:
  application:
    name: eureka-server
server:
  port: 9093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/,http://localhost:9092/eureka/
  instance:
    hostname: localhost:9093
    instance-id: eureka3

