spring:
  application:
    name: eureka-server
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://eureka2.com:9092/eureka/,http://eureka3.com:9093/eureka/
  instance:
    hostname: eureka1.com
    instance-id: eureka1
