spring:
  application:
    name: eureka-server
server:
  port: 9093
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:9091/eureka/,http://eureka2.com:9092/eureka/
  instance:
    hostname: eureka3.com
    instance-id: eureka3

